default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "postgres" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>

development:
  <<: *default
  database: emotion_diary_development

test:
  <<: *default
  database: emotion_diary_test

production:
  <<: *default
  database: emotion_diary_production
  username: emotion_diary
  password: <%= ENV["EMOTION_DIARY_DATABASE_PASSWORD"] %>