version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: emotion_diary_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/emotion_diary_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
      - DISABLE_SPRING=1
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/emotion_diary_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
      - DISABLE_SPRING=1
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: bundle exec sidekiq

volumes:
  postgres_data:
  redis_data:
